### ISSUE TITLE
Error: SSL Certificate verified

### ISSUE THREAD

**Issue by ST2Labs** [alerta/zabbix-alerta#10]
# Error HTTPS connection SSL Certificate Verified

It's necesary add option to enable sslverify = on | off 

I must to modify zabbix_alerta.py so:

response = requests.post(url, data=json.dumps(alert), headers=headers, timeout=2, verify=False)

Thanks

**Comment by satterly** [comment]
This is now supported using "profiles". See #11 and the "Advanced configuration" section in the README https://github.com/alerta/zabbix-alerta#advanced-configuration
