### ISSUE TITLE
'correlate' Alerta Input Missing

### ISSUE THREAD

**Issue by rewardian** [alerta/zabbix-alerta#23]
I'm still introducing myself to Alerta, otherwise I'd try updating zabbix-alerta, but it appears that the latest version of Alerta Client includes a "correlate" input which cannot be null or None.

My zabbix-alerta integration was failing until I removed the 'correlate' line from send_alert() in alerta-5.0.6-py2.7.egg/alertaclient/api.py on the Zabbix server.

**Comment by satterly** [comment]
This should be fixed in the next alerta client / API release. Thanks for reporting the issue.
