### ISSUE TITLE
After migrate alerta to another zabbix, the zabbix_alerta.log is not exists

### ISSUE THREAD

**Issue by lynch0227** [alerta/zabbix-alerta#3]
Hi 
Now I migrate the alerta to a new zabbix server(version 2.4.5), and I follow the below steps:
1. move the zabbix_alerta.py file into alertscripts folder
2. change it's mode to 777
3. install the argparse,requests python module
4. modify the debug parameter to False
5. follow the guide to configure zabbix
6. restart the alerta, apache server,zabbix server,zabbix agent

After I done these, I also can't get zabbix_alerta.log file, I don't know why.
Could you please help me on this?

**Comment by satterly** [comment]
It could be any one of the things you mention above. Turn on debug/trace for Zabbix and let me know if you find anything in the server logs.

**Comment by lynch0227** [comment]
Here is the debug log for zabbix when I close the agent process:

```
144303:20150810:095622.342 In DCconfig_get_poller_nextcheck() poller_type:1
144303:20150810:095622.342 End of DCconfig_get_poller_nextcheck():1439171822
144303:20150810:095622.342 unreachable poller #1 [got 0 values in 0.000139 sec, idle 5 sec]
144310:20150810:095622.486 alerter [sending alerts]
144310:20150810:095622.486 query [txnlev:0] [select a.alertid,a.mediatypeid,a.sendto,a.subject,a.message,a.status,mt.mediatypeid,mt.type,mt.description,mt.smtp_server,mt.smtp_helo,mt.smtp_email,mt.exec_path,mt.gsm_modem,mt.username,mt.pass
wd,a.retries from alerts a,media_type mt where a.mediatypeid=mt.mediatypeid and a.status=0 and a.alerttype=0 order by a.alertid]
144310:20150810:095622.486 alerter [sent alerts: 0 success, 0 fail in 0.000508 sec, idle 30 sec]
144299:20150810:095622.941 poller #2 [got 0 values in 0.000146 sec, getting values]
```

**Comment by satterly** [comment]
Try configuring a simple script that just logs zabbix alert attributes to a file when an alert is triggered and make sure that much is working first. Then replace the script with `zabbix_alerta.py` and see what happens. I suspect the script isn't being called as the zabbix server config is not right.
