### ISSUE TITLE
Error to send events and resource to zabbix

### ISSUE THREAD

**Issue by ghost** [alerta/zabbix-alerta#34]
Hi there!

I am facing the error below, could you please help me ?

2019-10-03 16:28:58.794 root[3933] MainThread INFO - [alerta] endpoint=http://192.168.224.141:8080/api key=cEvQK7FoZoNS-3EHPoyTkHFvTqMZA5uo0pD7KvPE
2019-10-03 16:28:58.795 root[3933] MainThread ERROR - send_alert() missing 2 required positional arguments: 'resource' and 'event'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/zabbix_alerta-3.5.0-py3.5.egg/zabbix_alerta.py", line 222, in main
    api.send_alert(**alert)
TypeError: send_alert() missing 2 required positional arguments: 'resource' and 'event'

Thanks.

**Comment by satterly** [comment]
This issue is blocked waiting on more information. The description or subsequent comments do not provide enough information to triage, investigate or resolve the issue. Please review the description against the [issue template](https://raw.githubusercontent.com/alerta/.github/master/.github/ISSUE_TEMPLATE/bug_report.md) and ensure all relevant information is included. If you do not know what is expected you can ask on [Gitter chat](https://gitter.im/alerta/chat).

**Comment by samirakazemi** [comment]
we are having the same issue on our side. We added configuration on our Zabbix side and are getting the same error message as thiagocpv 

> 2019-11-22 08:52:42.874 root[139513] MainThread ERROR - send_alert() missing 2 required positional arguments: 'resource' and 'event'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/zabbix_alerta.py", line 222, in main
    api.send_alert(**alert)
TypeError: send_alert() missing 2 required positional arguments: 'resource' and 'event'
2019-11-22 08:52:52.847 root[139568] MainThread INFO - [alerta]

The possible issue could be that on line 222 on zabbix_alerta.py, api calls the send_alert.
`api.send_alert(**alert)`

api is defined on line 217 as:
`api = Client(endpoint=args.endpoint, key=args.key, ssl_verify=args.sslverify)`

which belongs to
`from alertaclient.api import Client`

based on the documentation, the resource and event parameters are mandatory to be passed when send_alert is called, but they are not being passed on line 222 in zabbix_alerta.py

Do you mind investigating it a bit?

Thanks,

**Comment by satterly** [comment]
You need to make sure the default message of the "Forward to Alerta" action has the following:

```
resource={HOST.NAME1}
event={ITEM.KEY1}
environment=Production
severity={TRIGGER.SEVERITY}
status={TRIGGER.STATUS}
ack={EVENT.ACK.STATUS}
service={TRIGGER.HOSTGROUP.NAME}
group=Zabbix
value={ITEM.VALUE1}
text={TRIGGER.STATUS}: {TRIGGER.NAME}
tags={EVENT.TAGS}
attributes.ip={HOST.IP1}
attributes.thresholdInfo={TRIGGER.TEMPLATE.NAME}: {TRIGGER.EXPRESSION}
type=zabbixAlert
dateTime={EVENT.DATE}T{EVENT.TIME}Z
```

**Comment by RubenCapota** [comment]
I have the same problem.
The error I am getting is `ERROR: send_alert() missing 2 required positional arguments: 'resource' and 'event'
Aborted!`
The media type and action are configured the same as in the docs https://github.com/alerta/zabbix-alerta so the same as you described above. The zabbix version I am using is Zabbix 6.4
