### ISSUE TITLE
Zabbix 4.0 events are not changing status to ack

### ISSUE THREAD

**Issue by burakksglu** [alerta/zabbix-alerta#35]
**Issue Summary**
Zabbix 4.0 events are not changing status to ack

**Environment**
- OS: Linux
- API version: 4.0
- Deployment: Docker
- For self-hosted, WSGI environment: Docker

- Database: Postgres

- Server config:
  Auth enabled? No
  Auth provider?
  Customer views? No

- web UI version: 7.4.1
- CLI version: 7.4.1

**To Reproduce**
1. Go to zabbix and click ack button on problems list. 
2. Select Acknowledge (or change severity, this doesn't work as well)
3. Click Update button below
4. State or severity is not updated in Alerta (despite the event is received from zabbix)

Notes: In current documentation, update operations settings in action configuration doesn't exist. (only operation and recovery is mentioned). Moreover some parameters are missing in the examples for multiple zabbix servers and two way integration (eventid and triggerid). A more complete configuration example is below:

**Operation:**

```
resource={HOST.NAME1}
event={ITEM.KEY1}
environment=Production
severity={TRIGGER.SEVERITY}
status={TRIGGER.STATUS}
ack={EVENT.ACK.STATUS}
service=
group={TRIGGER.HOSTGROUP.NAME}
value={ITEM.VALUE1}
text={TRIGGER.STATUS}: {TRIGGER.NAME}
tags={EVENT.TAGS}
attributes.ip={HOST.IP1}
attributes.thresholdInfo={TRIGGER.TEMPLATE.NAME}: {TRIGGER.EXPRESSION}
dateTime={EVENT.DATE}T{EVENT.TIME}Z
type=zabbixAlert
attributes.zabbixUrl=http://zabbix_url
attributes.eventId={EVENT.ID}
attributes.triggerId={TRIGGER.ID}
```

**Recovery Operations**

```
resource={HOST.NAME1}
event={ITEM.KEY1}
environment=Production
severity={TRIGGER.SEVERITY}
status={TRIGGER.STATUS}
ack={EVENT.ACK.STATUS}
service=
group={TRIGGER.HOSTGROUP.NAME}
value={ITEM.VALUE1}
text={TRIGGER.STATUS}: {TRIGGER.NAME}
tags={EVENT.RECOVERY.TAGS}
attributes.ip={HOST.IP1}
attributes.thresholdInfo={TRIGGER.TEMPLATE.NAME}: {TRIGGER.EXPRESSION}
type=zabbixAlert
dateTime={EVENT.RECOVERY.DATE}T{EVENT.RECOVERY.TIME}Z
attributes.zabbixUrl=http://zabbix_url
attributes.eventId={EVENT.ID}
attributes.triggerId={TRIGGER.ID}
```

**Update Operations**

```
resource={HOST.NAME1}
event={ITEM.KEY1}
environment=Production
severity={TRIGGER.SEVERITY}
status={TRIGGER.STATUS}
ack={EVENT.ACK.STATUS}
service=
group={TRIGGER.HOSTGROUP.NAME}
value={ITEM.VALUE1}
text={TRIGGER.STATUS}: {TRIGGER.NAME}
tags={EVENT.RECOVERY.TAGS}
attributes.ip={HOST.IP1}
attributes.thresholdInfo={TRIGGER.TEMPLATE.NAME}: {TRIGGER.EXPRESSION}
type=zabbixAlert
dateTime={EVENT.RECOVERY.DATE}T{EVENT.RECOVERY.TIME}Z
attributes.zabbixUrl=http://zabbix_url
attributes.eventId={EVENT.ID}
attributes.triggerId={TRIGGER.ID}
```

**Comment by AlekseiSaff** [comment]
Is there are any updates on this issue?

**Comment by satterly** [comment]
Closing. Stale issue.
