### ISSUE TITLE
Zabbix 5.0 Support is not working %100, probably because of the breaking changes in Zabbix 5.0

### ISSUE THREAD

**Issue by burakksglu** [alerta/zabbix-alerta#39]
**Issue Summary**
Some actions are failing to send because Alerta can't decode sent information.

**Environment**
- OS: Linux
- Deployment: Docker 7.5.4

- Database: Postgres

- Server config:
  Auth enabled? Yes
  Auth provider? Basic
  Customer views? No

**To Reproduce**
1. Go to 'Zabbix 5.0'
2. Create a host with temperature discovery with °C or use of none English characters.
3. Configure the standard action template and start an alert. You can see that "value -> 61 \udcc2\udcb0C" displayed on error message in Zabbix 5.0
4. See error (include command output)

**Expected behavior**
To be able to decode or accept with errors. 

**Screenshots**
![image](https://user-images.githubusercontent.com/49399656/93059233-17438c80-f679-11ea-986a-9bbaf7d73df4.png)

![image](https://user-images.githubusercontent.com/49399656/93059560-8caf5d00-f679-11ea-9189-c12d58d43e69.png)

**Comment by burakksglu** [comment]
Hey @satterly ! Glad to see you here. In the first impression, what do think is the root cause of this issue?

**Comment by satterly** [comment]
Hey. It's almost certainly an encoding error. The "degree" symbol is not an ASCII character, I'm pretty sure. Will take a closer look when I get a chance.

**Comment by burakksglu** [comment]
Hey @satterly! Hope you're doing ok, where would be this encoding part? How can I help to fix this? I couldn't find the right code in my debug I guess.

**Comment by kolaynurdan** [comment]
The problem is also experienced in Turkish characters. Turkish characters also turn into unicode.

**Comment by satterly** [comment]
It would help a lot if you could provide an example from the '/var/log/zabbix/zabbix_alerta.log' log file generated by the `zabbix_alerta.py` script that demonstrates this problem. Thanks.

**Comment by burakksglu** [comment]
Hey @satterly ! I use docker containers in both applications therefore there was no zabbix_alerta.log but created a folder for it. So it created a log now. 

Here's an example of a Turkish charecter bug, it happens with host groups, centigrade degree, trigger names etc. also:

![image](https://user-images.githubusercontent.com/49399656/99394949-ceb28480-28f0-11eb-8c0c-0f671abdb464.png)


I've created a dummy trigger with Turkish charecters, here's the rigger:

![image](https://user-images.githubusercontent.com/49399656/99393729-cd805800-28ee-11eb-98c4-b6331aefbe48.png)


Here's the log:

![image](https://user-images.githubusercontent.com/49399656/99394629-403e0300-28f0-11eb-9529-d9d1d08356f9.png)

**Comment by burakksglu** [comment]
Hey @satterly ! Thank you for the fixes. I guess parsing is working right now but I'm getting this error now on the zabbix.

![image](https://user-images.githubusercontent.com/49399656/99951689-8c28f600-2d8f-11eb-9a09-3227fab136b6.png)

I'll try to add the below command to my dockerfile  for the fix:

ENV export LC_ALL=C.UTF-8 ENV export LANG=C.UTF-8

**Comment by satterly** [comment]
I actually think that was probably the root cause of the problem but I couldn't know how your server was setup. Click helpfully provided some pointers. Let's hope it works.

**Comment by burakksglu** [comment]
> I actually think that was probably the root cause of the problem but I couldn't know how your server was setup. Click helpfully provided some pointers. Let's hope it works.

Thank you! It's actually very similar to your Dockerfile. We use also containers it was working with 4.0 but we only changed the version to 5.0 which led us to incompatibility. Also we install this with pip3 install, do you think that might be an issue? Should I change it to your line in the dockerfile:

pip install --no-dir-cache 

Thanks,
Burak.

**Comment by burakksglu** [comment]
For now, it looks like it's working @satterly! Thank you for your effort. I'll monitor the situation today if something comes up I'll let you know.

Stay sane, stay safe :)
