### ISSUE TITLE
Zabbix 5.0 support for readme and zac

### ISSUE THREAD

**Issue by ihard** [alerta/zabbix-alerta#43]
Tool zac use deprecated metods (example user.updatemedia) and not usage for configure.
In the readme, the description is also for Zabbix 4 and it is not quite clear how to properly configure the integration in Zabbix 5.

**Comment by gpxlnx** [comment]
I would like this feature too.

**Comment by satterly** [comment]
Consider using Zabbix webhooks instead ... https://www.zabbix.com/documentation/current/en/manual/config/notifications/media/webhook
