### ISSUE TITLE
Improvement to README

### ISSUE THREAD

**Issue by bracoTuxbr** [alerta/zabbix-alerta#5]
Improvement to README

First I wanted to congratulate the system. I want to indicate information in the documentation of this zabbix alertscript.

To function properly, you should just leave in the "Send To" on the "Configuration -> User -> Media"

http://127.0.0.1:27018/api;94i_9kdHiee77lODjhqQ-xHTusxaS8mIP1bZap24

Regards

**Comment by satterly** [comment]
Thanks. I forgot to update the README to show how to add an API key to the configuration of the Alerta endpoint in Zabbix.
