### ISSUE TITLE
Not writing to log file / sending to API

### ISSUE THREAD

**Issue by poxin13** [alerta/zabbix-alerta#6]
If I look at my events in Zabbix and query the details of one I see that Action has been "Sent" to Alerta API type and to the correct recipient listed as:

Admin (Zabbix Administrator)
http://alerta.myserver.com:8080

I have a zabbix_alerta.log file created, owned by zabbix user with correct permissions.
Alertscript location set correctly in zabbix_server.conf

To test either permissions on the alert script I have zabbix_alerta.py and zabbix_alerta2.py in /alertscripts. One is owned by root, the other zabbix. Neither one of them seems to populate Alerta API or produce a log file.

Debug mode is False in the zabbix_alerta.py file.

Alerta API page on :8080 shows no heartbeat and "message": "not found",  under alerts

**Comment by poxin13** [comment]
Solved, I pulled down the .py file incorrectly :) Ignore the rookie mistake here _cough_

**Comment by satterly** [comment]
Ignoring :)
