### ISSUE TITLE
Alerta not receiving alerts from Zabbix and debug log is not being written to

### ISSUE THREAD

**Issue by raman325** [alerta/zabbix-alerta#9]
Hi there,

I saw someone post earlier about a similar issue, but I have DEBUG set to True in the script, so I am expecting logging. I have copied the python script to /usr/lib/zabbix/alertscripts/zabbix_alerta.py on my Zabbix application server (with appropriate permissions and ownership), and configured Zabbix as described in your Readme. Zabbix tells me that the action is being performed successfully, but when I query the Alerta API, I don't see any alerts, and /var/log/zabbix/zabbix_alerta.log has yet to be created. I then tried creating the log file with the appropriate permissions and ownership by touching it but it's still 0 bytes.

Of note, I noticed that logging and requests Python modules weren't on my Zabbix application server, so I installed them (argparse was already installed). Are there any other Python modules I could be missing? If it helps, I'm running Zabbix 2.4.3 and using Python 2.6.

Thanks for your help!

**Comment by satterly** [comment]
What happens when you try to run the script manually from the command line?
What error do you get?

**Comment by raman325** [comment]
Hmm, didn't think to do that, good idea. Looks like Python can't find argparse:
`Traceback (most recent call last):`
`File "zabbix_alerta.py", line 5, in <module>`
`import argparse`
`ImportError: No module named argparse`

Which is strange because when I try to install argpase, I get:
`Requirement already satisfied (use --upgrade to upgrade): argparse in /usr/lib/python2.6/site-packages`

Strangely, if I open up python interactively, I can see that the directory listed above is listed as an option:
`print sys.path`
`['', '/usr/lib64/python26.zip', '/usr/lib64/python2.6', '/usr/lib64/python2.6/plat-linux2', '/usr/lib64/python2.6/lib-tk', '/usr/lib64/python2.6/lib-old', '/usr/lib64/python2.6/lib-dynload', '/usr/lib64/python2.6/site-packages', '/usr/lib/python2.6/site-packages']`

Any ideas? This appears to be related to my system configuration rather than with the script.

**Comment by raman325** [comment]
I figured it out... I had a permissions issue with the Python modules which denied access to the user running the script. Once I fixed permissions, the script started working. The failure message the same when a module is missing and when it's inaccessible, and I got stuck going down the wrong path.

Thanks for your help!
